name: linting, testing, building
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting styles
        run: npm run lint:styles
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook-build
      - name: ui testing
        run: npm run test:ui:ci